services:
  audiobookshelf:
    container_name: audiobookshelf
    image: ghcr.io/advplyr/audiobookshelf
    restart: unless-stopped
    ports:
      - 13378:80
    volumes:
      - /mnt/audiobooks_unraid/:/audiobooks
      - /mnt/data_unraid/media/druckerzeugnisse/manga:/manga
      - /mnt/data_unraid/media/druckerzeugnisse/comics:/comics
      - /mnt/data_unraid/media/druckerzeugnisse/books:/books
      - /home/sebastian/docker/audiobookshelf/config/metadata/:/metadata
      - /home/sebastian/docker/audiobookshelf/config:/config
    labels:
      - traefik.enable=true
      - traefik.http.routers.audiobooks.rule=Host(`audiobook.borynsky.de`)
      - traefik.http.routers.audiobooks.entrypoints=websecure
      - traefik.http.routers.audiobooks.tls=true
      - traefik.http.routers.audiobooks.tls.certresolver=cloudflare
      - traefik.http.services.audiobooks.loadbalancer.server.port=80
    networks:
      - proxy
networks:
  proxy:
    external: true