services:
  sabnzbd:
    container_name: sabnzbd
    image: linuxserver/sabnzbd
    restart: unless-stopped
    ports:
      - "8080:8080"
      - "8090:8090"
    volumes:
      - /home/sebastian/docker/sabnzbd/config:/config
      - /mnt/data_unraid:/data:rw
    environment:
      - TZ=Europe/Berlin
      - PUID=1000
      - PGID=1000
    networks:
      - proxy

networks:
  proxy:
    external: true