services:
  vaultwarden:
    container_name: vaultwarden
    image: vaultwarden/server:latest-alpine
    restart: unless-stopped
    ports:
      - "8086:80"
    volumes:
      - /home/sebastian/docker/vaultwarden/config:/data
    environment:
      - TZ=Europe/Berlin
      - SERVER_ADMIN_EMAIL=sebastian_borynsky@icloud.com
      - ADMIN_TOKEN='${ADMIN_TOKEN}'
      - SIGNUPS_ALLOWED=false
      - INVITATIONS_ALLOWED=true
      - WEBSOCKET_ENABLED=false
    labels:
      - traefik.enable=true
      - traefik.http.routers.vaultwarden.rule=Host(`bitwarden.borynsky.de`)
      - traefik.http.routers.vaultwarden.entrypoints=websecure
      - traefik.http.routers.vaultwarden.tls=true
      - traefik.http.routers.vaultwarden.tls.certresolver=cloudflare
      - traefik.http.services.vaultwarden.loadbalancer.server.port=80
    networks:
      - proxy

networks:
  proxy:
    external: true
