services:
  radarr:
    container_name: radarr
    image: linuxserver/radarr
    restart: unless-stopped
    ports:
      - "7878:7878"
    volumes:
      - /home/sebastian/docker/radarr/config:/config
      - /mnt/data_unraid:/data
      - /mnt/data_unraid/media:/media
    environment:
      - TZ=Europe/Berlin
      - PUID=1000
      - PGID=1000
    networks:
      - proxy

networks:
  proxy:
    external: true