services:
  ddns-updater:
    image: qmcgaw/ddns-updater
    container_name: ddns-updater
    ports:
      - 8001:8000
    volumes:
      - /home/sebastian/docker/ddns-updater/config:/updater/data
    environment:
      - TZ=Europe/Berlin
      - PERIOD=5m
      - UPDATE_COOLDOWN_PERIOD=5m
      - PUBLICIP_FETCHERS=all
      - PUBLICIP_HTTP_PROVIDERS=all
      - PUBLICIPV4_HTTP_PROVIDERS=all
      - PUBLICIPV6_HTTP_PROVIDERS=all
      - PUBLICIP_DNS_PROVIDERS=all
      - PUBLICIP_DNS_TIMEOUT=3s
      - HTTP_TIMEOUT=10s

      # Web UI
      - LISTENING_ADDRESS=:8000
      - ROOT_URL=/

      # Other
      - LOG_LEVEL=info
      - LOG_CALLER=hidden
      - HEALTH_SERVER_ADDRESS=127.0.0.1:9999
    restart: unless-stopped
    networks:
      - proxy

networks:
  proxy:
    external: true