services:
  dozzle:
    container_name: dozzle
    image: amir20/dozzle
    restart: unless-stopped
    ports:
      - "9999:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DOZZLE_NO_ANALYTICS=true
      - DOZZLE_REMOTE_AGENT=10.10.10.4:7007
    healthcheck:
      test: ["CMD", "/dozzle", "healthcheck"]
      interval: 3s
      timeout: 30s
      retries: 5
      start_period: 30s
    networks:
      - proxy

networks:
  proxy:
    external: true

#Doku: https://dozzle.dev/guide/what-is-dozzle
