services:
  portainer:
    container_name: portainer
    image: portainer/portainer-ee
    restart: unless-stopped
    ports:
      - "9996:9000"
    labels:
      - hidden=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/sebastian/docker/portainer/config:/data
    environment:
      - TZ=Europe/Berlin
    networks:
      - proxy

networks:
  proxy:
    external: true