services:
  metube:
    container_name: metube
    image: ghcr.io/alexta69/metube
    restart: unless-stopped
    ports:
      - "9091:8081"
    volumes:
      - /mnt/data_unraid/usenet/komplett/metube:/downloads
    environment:
      - OUTPUT_TEMPLATE=%(channel)s/%(title)s.%(ext)s
      - TZ=Europe/Berlin
      - UID=1000
      - GID=1000
    networks:
      - proxy

networks:
  proxy:
    external: true