services:
  dockge:
    image: louislam/dockge
    container_name: dockge
    restart: unless-stopped
    ports:
      - 5001:5001
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config:/app/data
      - /home/sebastian/docker:/home/sebastian/docker
    environment:
      - DOCKGE_STACKS_DIR=/home/sebastian/docker
    networks:
      - proxy

networks:
  proxy:
    external: true
